version: '3.8'

services:
  portal-tecnico:
    build: .
    container_name: portal_tecnico
    ports:
      - "5555:5555"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - API_URL=${API_URL}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - CSRF_TOKEN=${CSRF_TOKEN}
      - USERS=${USERS}
      - SHAREPOINT=${SHAREPOINT}
    volumes:
      - .:/app
    networks:
      - flask_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M   # Reservando uma quantidade mínima de memória
          cpus: '0.5'     # Reservando meio núcleo de CPU

networks:
  flask_network:
    driver: bridge
